- hosts: node1
  gather_facts: false
  become: false
  vars_files:
    - ../vars-cloud.yml
    - ../vars-common.yml
  tasks:
    - name: clean node1
      shell: docker rm -fv $(docker ps -aq) 2>/dev/null || true && docker volume prune -f

    - name: pull mock1 server
      shell: docker pull {{ mock_image }}:{{ mock_version }}

    - name: deploy mock1 server
      docker_container:
        command: --workers {{ mock_workers_ct }}
        image: {{ mock_image }}:{{ mock_version }}
        name: mock
        network_mode: host
        state: started

- hosts: node2
  gather_facts: false
  become: false
  vars_files:
    - ../vars-cloud.yml
    - ../vars-common.yml
  tasks:
    - name: clean node2
      shell: docker rm -fv $(docker ps -aq) 2>/dev/null || true && docker volume prune -f

    - name: pull mock2 server
      shell: docker pull {{ mock_image }}:{{ mock_version }}

    - name: deploy mock2 server
      docker_container:
        command: --workers {{ mock_workers_ct }}
        image: {{ mock_image }}:{{ mock_version }}
        name: mock
        network_mode: host
        state: started

- hosts: node3
  gather_facts: false
  become: false
  vars_files:
    - ../vars-cloud.yml
    - ../vars-common.yml
  tasks:
    - name: clean node3
      shell: docker rm -fv $(docker ps -aq) 2>/dev/null || true && docker volume prune -f
      when: mock_workers | int >= 6

    - name: pull mock3 server
      shell: docker pull {{ mock_image }}:{{ mock_version }}
      when: mock_workers | int >= 3

    - name: deploy mock3 server
      docker_container:
        command: --workers {{ mock_workers_ct }}
        image: {{ mock_image }}:{{ mock_version }}
        name: mock
        network_mode: host
        state: started
      when: mock_workers | int >= 3

- hosts: node4
  gather_facts: false
  become: false
  vars_files:
    - ../vars-cloud.yml
    - ../vars-common.yml
  tasks:
    - name: clean node4
      shell: docker rm -fv $(docker ps -aq) 2>/dev/null || true && docker volume prune -f
      when: mock_workers | int >= 4

    - name: pull mock4 server
      shell: docker pull {{ mock_image }}:{{ mock_version }}
      when: mock_workers | int >= 4

    - name: deploy mock4 server
      docker_container:
        command: --workers {{ mock_workers_ct }}
        image: {{ mock_image }}:{{ mock_version }}
        name: mock
        network_mode: host
        state: started
      when: mock_workers | int >= 4

- hosts: node5
  gather_facts: false
  become: false
  vars_files:
    - ../vars-cloud.yml
    - ../vars-common.yml
  tasks:
    - name: clean node5
      shell: docker rm -fv $(docker ps -aq) 2>/dev/null || true && docker volume prune -f
      when: mock_workers | int >= 5

    - name: pull mock5 server
      shell: docker pull {{ mock_image }}:{{ mock_version }}
      when: mock_workers | int >= 5

    - name: deploy mock5 server
      docker_container:
        command: --workers {{ mock_workers_ct }}
        image: {{ mock_image }}:{{ mock_version }}
        name: mock
        network_mode: host
        state: started
      when: mock_workers | int >= 5

- hosts: node6
  gather_facts: false
  become: false
  vars_files:
    - ../vars-cloud.yml
    - ../vars-common.yml
  tasks:
    - name: clean node6
      shell: docker rm -fv $(docker ps -aq) 2>/dev/null || true && docker volume prune -f
      when: mock_workers | int >= 6

    - name: pull mock6 server
      shell: docker pull {{ mock_image }}:{{ mock_version }}
      when: mock_workers | int >= 6

    - name: deploy mock6 server
      docker_container:
        command: --workers {{ mock_workers_ct }}
        image: {{ mock_image }}:{{ mock_version }}
        name: mock
        network_mode: host
        state: started
      when: mock_workers | int >= 6
