'use strict';
require('./unit/configuration-api_test.js');
require('./unit/bidirectionalityHttp-test.js');
require('./unit/HTTP_commands_test.js');
require('./unit/HTTP_get-configuration_test.js');
require('./unit/HTTP_reveice_measures-test.js');
require('./unit/commandsPolling-test.js');
require('./unit/startup-test.js');
require('./unit/subscription-management_test.js');
require('./unit/attribute-alias_test.js');
require('./unit/supportThinkingThingModules_test.js');